Resources:
  ### IAM Role
  DatabricksClusterSageMakerAccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: databricks-cluster-sagemaker-access-role
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: get-role-inline-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: iam:GetRole"
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/databricks-cluster-sagemaker-access-role'
  ### Instance Profile
  DatabricksClusterSageMakerAccessRoleInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref DatabricksClusterSageMakerAccessRole

  ### Create SageMaker Notebook
  SageMakerNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      NotebookInstanceName: databricks-on-aws-immersion-day
      InstanceType: ml.t3.large
      RoleArn: !GetAtt DatabricksClusterSageMakerAccessRole.Arn
      PlatformIdentifier: notebok-al2-v2
